name: Continuous Integration

on:
  push:
    branches: # This configuration does not affect the page_build event above
      - master
        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100

    - name: Setup Dotnet Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
        source-url: https://nuget.pkg.github.com/Dualog/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup Nuget Config
      run: sed 's/GITHUB_TOKEN/${{ secrets.NUGET_TOKEN }}/g' .nuget.config > nuget.config

    - name: Build packages
      run: dotnet build -c Release /p:PublicRelease=true

    - name: Pack packages
      run: dotnet pack -c Release /p:PublicRelease=true
      
    - name: Publish Package
      run: dotnet nuget push ./**/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
